# Generated by Django 5.0.4 on 2024-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='position_lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='position_lng',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
