# Generated by Django 5.0.4 on 2024-04-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_position_lat_report_position_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='position_lat',
        ),
        migrations.RemoveField(
            model_name='report',
            name='position_lng',
        ),
    ]
